version: '3.8'

services:
  fastapi-app:
    build: .
    ports:
      - "8000:8080"
    volumes:
      - ./app:/code/app
    environment:
      - UVICORN_HOST=0.0.0.0
      - UVICORN_PORT=8080
    restart: always
